# name=input("enter your name")
# age=input("enter your age")
# name,age=input("enter your name and age ").split()
# print("your name is",name)
# print("your age is",age)
name , age = input("enter your name and age ").split(",")
print(name)
print(age)